Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "vm-#{i}" do |vm|
      # ubuntu 24.04 arm64
      vm.vm.box = "bento/ubuntu-24.04"
      vm.vm.hostname = "vm-#{i}"
      vm.vm.network "private_network", ip: "10.10.0.#{i+10}"
      vm.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "2048"
      end
    end
  end
end
